
version: '3.8'
services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookReviewDB
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

